"""Re-performing a discovering action, INCLUDING the values that were typed.

Contract: qa/contracts/crawl-traversal.md CR2 (fill-value replay) and CR7
(replaying widens nothing). A new module rather than more lines in
`explore_return.py`, per the contract's "How a unit is verified" section;
`explore_return.py` keeps the recursion, the bound and the fingerprint check,
and delegates "actually re-do the action" to here.

**The gap this closes.** `_replay_discovery` used to re-perform a discovering
edge with `rt.session.click(edge.target)` and nothing else. Two screens were
therefore unreachable by `return_to`:

1. a screen discovered BY a typed action (an X10-b `FILL`/`SELECT` edge whose
   `onchange` navigated) — the replay clicked a text input, which does nothing,
   and the crawl reported "landed on a different screen";
2. a screen reachable only behind a filled, SUBMITTED form — the replay clicked
   the submit control of a form that was now empty, so the app re-rendered the
   form instead of the screen behind it.

**What this is NOT (CR7).** This originates nothing. Every value re-issued here
was generated by `synthetic_values.py` and typed once already, on this same
crawl, through `explore_typing.type_form`, under all four X10-b conditions. The
replay re-issues that recorded value to that recorded target and no other. And
it does not trust "it was typed once before": every replay passes through the
SAME `typing_allowed` / `typing_target_allowed` gate a fresh type passes
through, re-evaluated against the CURRENT run's policy. A recorded value whose
gate now refuses is not replayed — it is reported as a refusal.

**And X7 binds it too** (`ISS-t165-crawl-traversal-1`). "The host is re-checked
after EVERY action" is unamended by this contract, so every action issued here
is followed by `check_destination`, with an `OFF_DOMAIN_REFUSED` edge and a
NAVIGATION issue recorded exactly as `explore_node.try_action` and
`explore_typing._type_one` record theirs. That an action was permitted once is
no evidence about where its re-render lands the second time.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from autotester.browser.session import NavigationRefused, check_destination
from autotester.schema.enums import Action, EdgeOutcome, IssueKind
from autotester.schema.screen_graph import ElementRef, ScreenEdge
from autotester.stages.explore_safety import typing_allowed, typing_target_allowed

if TYPE_CHECKING:
    from autotester.stages.explore import ExploreRuntime

TYPED_ACTIONS = frozenset({Action.FILL, Action.SELECT})
GATE_REFUSED = ("the recorded value for {target!r} is not replayable under this run's "
                "policy (the X10-b typing gate refuses it now)")
OFF_DOMAIN = ("re-performing {target!r} landed off-domain and was refused: {why}")


@dataclass(frozen=True)
class TypedAction:
    """One value the crawl really typed, remembered so it can be re-issued.

    Held in memory on the `ExploreRuntime` for the life of the crawl and NEVER
    persisted: a typed value is synthetic and non-PII by X10-b construction, but
    writing values to disk would create a second place a value can live, which
    is exactly what `SecretRef` discipline exists to prevent (C5, PP5).
    """

    node_id: str
    element: ElementRef
    action: Action
    value: str


def record(rt: ExploreRuntime, node_id: str, element: ElementRef,
           action: Action, value: str) -> None:
    """Remember a value `explore_typing` just typed, so CR2 can re-issue it."""
    rt.typed.setdefault(node_id, []).append(
        TypedAction(node_id=node_id, element=element, action=action, value=value))


def _gated(rt: ExploreRuntime, typed: TypedAction) -> bool:
    """CR7: the same gate a FRESH type passes, re-evaluated now. Never a
    "was this typed once before" shortcut."""
    return typing_allowed(rt.policy) and typing_target_allowed(typed.element)


def _issue(rt: ExploreRuntime, typed: TypedAction) -> None:
    if typed.action is Action.SELECT:
        rt.session.select_option(typed.element.selector, typed.value)
    else:
        rt.session.fill(typed.element.selector, typed.value)


def _element_for(rt: ExploreRuntime, edge: ScreenEdge) -> ElementRef:
    """The element `edge` acted on, so a refusal is recorded against the real
    control. A node dropped from the crawl leaves only what the edge itself
    carries — a named, selectable stand-in, never a silent omission."""
    node = rt.nodes.get(edge.from_node)
    for element in node.elements if node is not None else []:
        if element.selector == edge.target:
            return element
    return ElementRef(role="", selector=edge.target, name=edge.name or "")


def _landed_on_domain(rt: ExploreRuntime, node_id: str, element: ElementRef,
                      action: Action) -> str | None:
    """X7: the host is re-checked after EVERY action — replays included.

    `ISS-t165-crawl-traversal-1`: this was the one action path in the crawler
    that did not. `explore_node.try_action` and `explore_typing._type_one` both
    re-check where the browser landed and record `OFF_DOMAIN_REFUSED`; the
    replay reported a plain success, so a re-render that redirected somewhere
    else the second time round was invisible. Replaying an already-approved
    action says nothing about where it lands THIS time.

    Returns None when the landing is in-domain, else the refusal's reason —
    having first recorded it exactly as the two existing call sites do.
    """
    try:
        check_destination(rt.project, rt.session.current_url())
    except NavigationRefused as exc:
        return _refusal_of(rt, node_id, element, action, exc)
    return None


def _refusal_of(rt: ExploreRuntime, node_id: str, element: ElementRef,
                action: Action, exc: NavigationRefused) -> str:
    """Record an off-domain replay the way `try_action` records one — a
    NAVIGATION issue plus an `OFF_DOMAIN_REFUSED` edge, so X16's surfaces show
    it — and return the reason `_replay_discovery` reports upward."""
    from autotester.stages.explore_node import add_issue, record_edge  # cycle: import at use

    add_issue(rt, node_id, IssueKind.NAVIGATION, str(exc))
    node = rt.nodes.get(node_id)
    if node is not None:
        record_edge(rt, node, element, action, EdgeOutcome.OFF_DOMAIN_REFUSED, str(exc))
    return OFF_DOMAIN.format(target=element.name or element.selector, why=exc)


def replay_fills(rt: ExploreRuntime, node_id: str, *, skip: str | None = None) -> str | None:
    """CR2: re-issue every value recorded on `node_id`, in the order typed.

    `skip` is a selector to leave alone — used when the discovering edge is
    ITSELF that typed action, so it is not issued twice. Returns None on
    success, or the reason it could not be done.
    """
    for typed in rt.typed.get(node_id, []):
        if skip is not None and typed.element.selector == skip:
            continue
        if not _gated(rt, typed):
            return GATE_REFUSED.format(target=typed.element.selector)
        try:
            _issue(rt, typed)
        except NavigationRefused as exc:  # X7: the guard refused the fill itself
            return _refusal_of(rt, node_id, typed.element, typed.action, exc)
        except Exception as exc:
            return (f"re-issuing the recorded value for {typed.element.selector!r} raised "
                    f"{type(exc).__name__}: {exc}")
        # X7 after EVERY action: a fill whose `onchange` auto-submits can leave
        # the domain without any click being replayed at all. SETTLE FIRST --
        # `BrowserSession.fill()` is a bare Playwright fill that does not wait for
        # a JS-triggered navigation, so an unsettled `current_url()` still reads
        # the old, on-domain URL and the check silently passes.
        rt.session.settle(timeout_ms=rt.bounds.settle_ms)
        refused = _landed_on_domain(rt, node_id, typed.element, typed.action)
        if refused is not None:
            return refused
    return None


def _recorded_for(rt: ExploreRuntime, edge: ScreenEdge) -> TypedAction | None:
    return next((t for t in rt.typed.get(edge.from_node, [])
                 if t.element.selector == edge.target and t.action is edge.action), None)


def perform(rt: ExploreRuntime, edge: ScreenEdge) -> str | None:
    """Re-perform `edge` from the screen it was recorded on. None on success.

    A typed discovering edge is re-issued as the typed action it was; any other
    edge is re-clicked, with the form it submits refilled first so a screen
    behind a submitted form is genuinely re-entered rather than bouncing off an
    empty form.
    """
    if edge.action in TYPED_ACTIONS:
        typed = _recorded_for(rt, edge)
        if typed is None:
            return (f"{edge.action.value} edge {edge.name or edge.target!r} has no recorded "
                    "value to re-issue (it was typed before this crawl recorded values)")
        refused = replay_fills(rt, edge.from_node, skip=edge.target)
        if refused is not None:
            return refused
        if not _gated(rt, typed):
            return GATE_REFUSED.format(target=edge.target)
        try:
            _issue(rt, typed)
        except NavigationRefused as exc:
            return _refusal_of(rt, edge.from_node, typed.element, edge.action, exc)
        except Exception as exc:
            return (f"re-issuing {edge.name or edge.target!r} raised "
                    f"{type(exc).__name__}: {exc}")
        rt.session.settle(timeout_ms=rt.bounds.settle_ms)
        return _landed_on_domain(rt, edge.from_node, typed.element, edge.action)
    refused = replay_fills(rt, edge.from_node)
    if refused is not None:
        return refused
    element = _element_for(rt, edge)
    try:
        rt.session.click(edge.target)
    except NavigationRefused as exc:
        return _refusal_of(rt, edge.from_node, element, edge.action, exc)
    except Exception as exc:
        return (f"re-performing {edge.name or edge.target!r} raised "
                f"{type(exc).__name__}: {exc}")
    rt.session.settle(timeout_ms=rt.bounds.settle_ms)
    # X7, the gap ISS-t165-crawl-traversal-1 filed: a replayed click that lands
    # off-domain used to return success from here.
    return _landed_on_domain(rt, edge.from_node, element, edge.action)
